### ISSUE TITLE
Add READMe

### ISSUE THREAD

**Issue by itxshakil** [itxshakil/pfx-to-pem-converter#2]
### Issue Description: Add README for Project

**Overview:**
The project is a web-based tool for converting PFX (PKCS#12) files to PEM format, which is typically used for SSL/TLS certificate management. The tool allows users to upload a `.pfx` file, enter the corresponding password, and then download the extracted private key and certificate in a ZIP archive format. This tool is designed to provide a secure, user-friendly experience with a focus on privacy, ensuring that uploaded files are deleted after processing.

**Objective:**
Add a comprehensive README file for the project to provide clear instructions and details for developers and users. The README will include the following sections:

1. **Project Overview**: A brief description of what the project does and its functionality.
2. **Features**: Key features of the tool such as file upload, password protection, and automatic deletion of files after conversion.
3. **Installation**: Step-by-step instructions on how to set up the project on a local machine or server.
4. **Usage**: Detailed guidance on how to use the tool, including uploading files and handling errors.
5. **Security Considerations**: Explanation of CSRF protection, file validation, and automatic file deletion after download.
6. **Dependencies**: List of any required libraries or packages (e.g., PHP, OpenSSL, ZipArchive).
7. **Contributing**: Guidelines for contributing to the project, including code style and issue reporting.
8. **License**: Information about the project’s licensing.

---

### Expected Deliverables:
- A README.md file added to the root of the repository containing the above sections.
- The README should be formatted with markdown and include links to any relevant resources (e.g., OpenSSL documentation, PHP documentation).

**Comment by nhathao10** [comment]
Hello ! Can I help you this issue?

**Comment by itxshakil** [comment]
> Hello ! Can I help you this issue?

Added detail in description of the issue.
